version: '3.4'
services:
  frontend:
    stdin_open: true
    image: frontend
    build:
      context: .
      dockerfile: ../frontend/Dockerfile
  backend:
    image: backend
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    ports:
      - 80
      - 443
