version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Dockerfile
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build: 
        context: ../frontend
        dockerfile: Dockerfile
    
